// TypeScript code generator — emits .ts with type annotations
// Thin wrapper over the JavaScript generator that adds type declarations.

import type { GraphIR } from '../ir/graph.js';

import { generateJavaScriptFixed, type GenerateJsOptions } from './javascript.js';

export interface GenerateTsOptions extends GenerateJsOptions {}

export function generateTypeScript(
  graph: GraphIR,
  options: GenerateTsOptions = {},
): string {
  // Generate the JS code and prepend TS type declarations
  const jsCode = generateJavaScriptFixed(graph, options);

  const header = `// Generated by model2webnn — TypeScript output
// Source model: ${graph.name} (${graph.format})

// Type declarations for WebNN API (Chromium)
type MLDeviceType = 'cpu' | 'gpu' | 'npu';
type MLPowerPreference = 'default' | 'high-performance' | 'low-power';

interface MLContextOptions {
  deviceType?: MLDeviceType;
  powerPreference?: MLPowerPreference;
}

interface MLOperandDescriptor {
  dataType: string;
  shape: (number | string)[];
}

declare const navigator: Navigator & {
  ml: {
    createContext(options?: MLContextOptions): Promise<MLContext>;
  };
};

interface MLContext {
  createTensor(descriptor: MLTensorDescriptor): Promise<MLTensor>;
  writeTensor(tensor: MLTensor, data: AllowSharedBufferSource): undefined;
  readTensor(tensor: MLTensor): Promise<ArrayBuffer>;
  dispatch(graph: MLGraph, inputs: Record<string, MLTensor>, outputs: Record<string, MLTensor>): undefined;
  destroy(): undefined;
}

interface MLTensorDescriptor extends MLOperandDescriptor {
  readable?: boolean;
  writable?: boolean;
}

interface MLTensor {
  readonly dataType: string;
  readonly shape: readonly number[];
  readonly readable: boolean;
  readonly writable: boolean;
  destroy(): undefined;
}

type AllowSharedBufferSource = ArrayBufferView | ArrayBuffer;

interface MLGraph {
  destroy(): undefined;
}

interface MLGraphBuilder {
  input(name: string, descriptor: MLOperandDescriptor): MLOperand;
  constant(descriptor: MLOperandDescriptor, data: ArrayBufferView): MLOperand;
  build(outputs: Record<string, MLOperand>): Promise<MLGraph>;
  // Operations are accessed dynamically
  [op: string]: any;
}

declare class MLGraphBuilder {
  constructor(context: MLContext);
}

interface MLOperand {}

`;

  return header + jsCode;
}
